### ISSUE TITLE
Review naming

### ISSUE THREAD

**Issue by samdark** [yiisoft/security#3]
Naming should be reviewed before first release. Please comment if you see a way to improve public API.

**Comment by sergeymakinen** [comment]
Just a side note: it's better to follow "Exception"-suffix convention for exceptions.

**Comment by samdark** [comment]
Why?

**Comment by sergeymakinen** [comment]
Because it makes them distinctive - as they are.

**Comment by samdark** [comment]
"Exception" suffix added.

**Comment by alexkart** [comment]
What about `PasswordHash` and `TokenMask` instead of `PasswordHasher` and `TokenMasker`?

**Comment by samdark** [comment]
`PasswordHash` sounds like an object storing a password hash. `PasswordHash::hash()` looks weird to me.

`TokenMask` sounds OK if we'll change method names as well:

- `TokenMask::apply()`
- `TokenMask::remove()`
